### ISSUE TITLE
jvm加载jar包顺序问题

### ISSUE THREAD

**Issue by yaoyuanyy** [saaavsaaa/saaavsaaa.github.io#1]
https://www.cnblogs.com/saaav/p/7716179.html，看了您的文章。有个疑问请教下，最后的问题通过将http-1.1.0.jar改成zzzhttp-1.1.0.jar解决了，但是本质原因是什么呢，没有从文章中看到

**Comment by co-develop-drv** [comment]
直接改名字这个方式并不正确。是当时在线上临时解决问题碰运气的方法，当时的情况应该是走流程改这个问题需要一点时间，所以就临时改一下文件名，看看能不能让inode比冲突的jar的大，其实这个方法并不一定总能成功。正确的应对方式当时可能是因为毕竟是用的第三方公司的包，不好明说，总之就是去掉一份代码就好了，同一个包同名类不应该存在。好奇怪，5月份提的问题？我之前居然没看到过-_-!!!

**Comment by co-develop-drv** [comment]
好奇怪，5月份提的问题？我之前居然没看到过-_-!!!
